### ISSUE TITLE
Caching issue causing an error loading the Magnific Popup plugin

### ISSUE THREAD

**Issue by tanahel-udem** [wet-boew/cdts-sgdc#1160]
The following error sometimes show up making the magnific popup unresponsive. The error shows up on v5.0.0 after refreshing the page. A hard refresh normally solves the issue. The error is present on the sample page: https://cdts.service.canada.ca/app/cls/WET/gcintranet/v5_0_0/cdts/samples/gctoolsmodal-en.html#gctools

```
 Uncaught TypeError: Cannot read properties of null (reading 'insertBefore')
    at e.yepnope.injectJs (wet-boew.js:1972:7686)
    at wet-boew.js:1972:4461
```

**Comment by ahmad-shahid** [comment]
Hello, what steps would I have to take to reproduce this error?

**Comment by tanahel-udem** [comment]
On Edge version 124.0.2478.97
1. Go to the [gctoolsmodal sample](https://cdts.service.canada.ca/app/cls/WET/gcintranet/v5_0_0/cdts/samples/gctoolsmodal-en.html#gctools).
2. Open the console.
3. Refresh the page multiple times until the error shows up.
4. Once the error is logged try opening the GCTools and notice no popups open.

**Comment by ahmad-shahid** [comment]
We'll take a look at this as soon as we get the new Edge update.

**Comment by chyne** [comment]
We're seeing similar issue in 4.0.47 (in Chrome):

TypeError: Cannot read properties of null (reading 'insertBefore')
    at e.yepnope.injectJs (wet-boew.js:1947:7686)
    at wet-boew.js:1947:4461

In our case we noticed thanks to intermittent reports of DataTables AJAX call not firing. First reports started coming around the time this issue was opened.

**Comment by chyne** [comment]
I am also able to reproduce this issue on the 4.0.47 page:
https://cdts.service.canada.ca/app/cls/WET/gcintranet/v4_0_47/cdts/samples/gctoolsmodal-en.html#gctools

Chrome 125.0.6422.142

**Comment by chyne** [comment]
I can even reproduce the issue on the CDTS home page: https://cenw-wscoe.github.io/sgdc-cdts/docs/index-en.html

```
Uncaught 
TypeError: Cannot read properties of null (reading 'insertBefore')
    at e.yepnope.injectJs (wet-boew.js:1999:7686)
    at wet-boew.js:1999:4461
```

CDTS/WET fails to load and all WET/CDTS functionality is broken (example, menu doesn't load):

![image](https://github.com/user-attachments/assets/e522e746-67ab-4a0f-9e67-158b2416f72f)

**Comment by chyne** [comment]
This might be an extension issue. In the WET repo a user reported a similar issue that they traced to VueJS extension. In my case LastPass extension seems to have been the issue. Removing and re-installing it to force an update to a newer version seems to have resolved it for me.
